### PR TITLE
bump spark to 1.6.1

### PR DESCRIPTION
**Pull request by c4po**

### CODE REVIEW

**Comment by vijayaguru** [comment]
@c4po Did you try to deploy this spark 1.6.1 containers on kubernetes?
I am trying to run a simple word count example "sc.parallelize("a b c a a b b c".split(" ").toSeq).countByValue". This works fine in spark 1.5.2 containers deployed on kubernetes.
When I run this on spark 1.6.1 cluster, the job fails with few exceptions.

**Comment by c4po** [comment]
@vijayaguru 
I have deployed this spark 1.6.1 cluster on kubernetes and don't have issue to run your sample code and my other code.
But I do see errors when zeppelin connect to the spark 1.6.1.

**Comment by vijayaguru** [comment]
@c4po Which version of kubernetes are you using?
I am trying with kubernetes 1.2.4 deployed on openstack coreos VMs. 
Kubernetes was deployed using ansible playbooks -  https://github.com/kubernetes/contrib/tree/master/ansible. 
The spark was deployed on kubernetes using https://github.com/kubernetes/kubernetes/tree/v1.2.4/examples/spark
I am using Spark job server as driver https://hub.docker.com/r/velvia/spark-jobserver/

If there is a single spark executor, the example job runs fine. If there are multiple spark executors, the job is trying to shuffle data between the executors. 
The shuffle fails with the following exception. The spark scheduler schedules the task in another executor and completes it. But the job's performance is really poor.

My spark application has two executors in worker pods 172.16.2.5 and 172.16.45.4.
One of the executor has valid ip/port 172.16.2.5:42239. The other executor has 
invalid ip/port 172.16.45.0:41169, which should be 172.16.45.4:41169.
This is the reason for the shuffle failure.
I am trying to find out whether this is specific to my deployment.
Does your spark application have multiple executors? What spark driver are you using?

<snip>
[2016-06-09 11:30:13,631] WARN  k.scheduler.TaskSetManager [] [akka://JobServer/user/context-supervisor/functional_new] - Lost task 0.0 in stage 1.0 (TID 2, 172.16.2.5): FetchFailed(BlockManagerId(0, 172.16.45.0, 41169), shuffleId=0, mapId=0, reduceId=0, message=
org.apache.spark.shuffle.FetchFailedException: Failed to connect to /172.16.45.0:41169
	at org.apache.spark.storage.ShuffleBlockFetcherIterator.throwFetchFailedException(ShuffleBlockFetcherIterator.scala:323)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator.next(ShuffleBlockFetcherIterator.scala:300)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator.next(ShuffleBlockFetcherIterator.scala:51)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:32)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:152)
	at org.apache.spark.Aggregator.combineCombinersByKey(Aggregator.scala:58)
	at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala:83)
	at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:98)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed to connect to /172.16.45.0:41169
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:216)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:167)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$1.createAndStart(NettyBlockTransferService.scala:90)
	at org.apache.spark.network.shuffle.RetryingBlockFetcher.fetchAllOutstanding(RetryingBlockFetcher.java:140)
	at org.apache.spark.network.shuffle.RetryingBlockFetcher.access$200(RetryingBlockFetcher.java:43)
	at org.apache.spark.network.shuffle.RetryingBlockFetcher$1.run(RetryingBlockFetcher.java:170)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.net.ConnectException: Connection refused: /172.16.45.0:41169
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	... 1 more

)
</snip>

**Comment by c4po** [comment]
@vijayaguru I'm using kubernetes 1.2.4 deployed with Debian on AWS EC2 with the `kube-up.sh` 
Spark cluster was deployed using same script as you. but without Zeppelin. It has 1 master node and 2 worker nodes. 
I was just login to the master node and run `spark-shell` to test your script.
I also run this example to test multi executors, and don't see any issues

```
./bin/spark-submit --class org.apache.spark.examples.SparkPi \
    --num-executors 3 \
    lib/spark-examples*.jar \
    10
```

**Comment by zmerlynn** [comment]
If you haven't tested this with Zeppelin, please find a version combination that works. I had the option of 1.6.x the last time I bumped, but there wasn't yet a Zeppelin version that was compatible.

**Comment by c4po** [comment]
the latest zeppelin only support spark 1.6.0. https://zeppelin.incubator.apache.org/releases/zeppelin-release-0.5.6-incubating.html
do you think we need we need wait for new zeppelin release or downgrade spark to 1.6.0?
In our case, we don't need zeppelin. Just need an image with spark1.6 can be scheduled in kubernetes.

**Comment by zmerlynn** [comment]
This image is tied to this curated example: https://github.com/kubernetes/kubernetes/tree/master/examples/spark . So yes, for the moment.

**Comment by c4po** [comment]
* The image will be built with 1.6.1 tag, it won't break the script in the example. 
* Spark 1.6 has been release for 5 month, I don't see any value to deploy a spark 1.5 cluster on kubernetes.
* I can create a PR to update the README file in the kubernetes example repo after this change.

**Comment by zmerlynn** [comment]
FWIW, 1.6.1 may interact happily with that Zeppelin, but I don't have the time to test it. I had luck with with other patch versions.

Yes, the example will still deploy because it's using explicit tags, but for a version bump we should find a combination of the two together I can push. That example is essentially what I was using to spot check the version bumps.

**Comment by radek1st** [comment]
I'm interested in using 1.6.1 too. I was about to start preparing a PR with a bump when I saw this.

**Pull request closed without merging**
